version: '3.8'

services:
  # The Go Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      # Pass environment variables to the Go app
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - GIN_MODE=release
    networks:
      - internal-net

  # The Redis Database
  redis:
    image: "redis:7-alpine"
    restart: always
    networks:
      - internal-net

  # The Nginx Reverse Proxy
  nginx:
    image: "nginx:1.25-alpine"
    restart: always
    ports:
      - "80:80" # Map host port 80 to container port 80
      - "443:443" # For future HTTPS
    volumes:
      - ./client/dist:/usr/share/nginx/html # Mount the built frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount our Nginx config
    depends_on:
      - app
    networks:
      - internal-net
      - public-net

networks:
  internal-net:
    internal: true
  public-net: {}