# Use the official Go image
FROM golang:1.21-alpine

# Set working directory inside the container
WORKDIR /app

# Copy and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Install Air for live-reloading
RUN go install github.com/cosmtrek/air@latest

# Copy the application source code
COPY . .

# Expose port
EXPOSE 8080

# Command to run the application with live-reloading
CMD ["air", "-c", "server/.air.toml"]