# --- Build Stage ---
FROM golang:1.23.10-alpine as builder

WORKDIR /app

# Copy Go modules and source code
COPY go.mod go.sum ./
COPY server/go.mod server/go.sum ./server/
COPY core/go.mod core/go.sum ./core/

RUN go mod download

COPY . .

# Build the Go binary
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /alignment-server ./server/cmd/server

# --- Final Stage ---
FROM alpine:latest

WORKDIR /root/

# Copy the binary from the builder stage
COPY --from=builder /alignment-server .

# Add a non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Switch to the non-root user
USER appuser

EXPOSE 8080

# Command to run the application
CMD ["./alignment-server"]