package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/swaggo/http-swagger"
	"golang.org/x/sync/semaphore"
	"github.com/xjhc/alignment/core"
	_ "github.com/xjhc/alignment/server/docs" // docs is generated by Swagger
	"github.com/xjhc/alignment/server/internal/actors"
	"github.com/xjhc/alignment/server/internal/admin"
	"github.com/xjhc/alignment/server/internal/admission"
	"github.com/xjhc/alignment/server/internal/auth"
	"github.com/xjhc/alignment/server/internal/comms"
	"github.com/xjhc/alignment/server/internal/events"
	"github.com/xjhc/alignment/server/internal/game"
	"github.com/xjhc/alignment/server/internal/handlers"
	"github.com/xjhc/alignment/server/internal/health"
	"github.com/xjhc/alignment/server/internal/lifecycle"
	"github.com/xjhc/alignment/server/internal/logger"
	"github.com/xjhc/alignment/server/internal/mcp"
	"github.com/xjhc/alignment/server/internal/metrics"
	"github.com/xjhc/alignment/server/internal/store"
	"golang.org/x/time/rate"
)

// Global semaphore for limiting concurrent action processing
var actionSemaphore = semaphore.NewWeighted(100)

// IPRateLimiter manages per-IP rate limiting
type IPRateLimiter struct {
	limiters map[string]*rate.Limiter
	mu       sync.RWMutex
	rate     rate.Limit
	burst    int
}

// NewIPRateLimiter creates a new per-IP rate limiter
func NewIPRateLimiter(r rate.Limit, b int) *IPRateLimiter {
	return &IPRateLimiter{
		limiters: make(map[string]*rate.Limiter),
		rate:     r,
		burst:    b,
	}
}

// GetLimiter returns the rate limiter for a given IP
func (i *IPRateLimiter) GetLimiter(ip string) *rate.Limiter {
	i.mu.Lock()
	defer i.mu.Unlock()

	limiter, exists := i.limiters[ip]
	if !exists {
		limiter = rate.NewLimiter(i.rate, i.burst)
		i.limiters[ip] = limiter
	}

	return limiter
}

// CleanupStale removes stale limiters (called periodically)
func (i *IPRateLimiter) CleanupStale() {
	i.mu.Lock()
	defer i.mu.Unlock()

	for ip, limiter := range i.limiters {
		// Remove limiters that haven't been used recently
		if limiter.Tokens() == float64(i.burst) {
			delete(i.limiters, ip)
		}
	}
}

// getClientIP extracts the real client IP from the request
func getClientIP(r *http.Request) string {
	// Check X-Forwarded-For header first (for proxies)
	if xff := r.Header.Get("X-Forwarded-For"); xff != "" {
		// Take the first IP from comma-separated list
		ips := strings.Split(xff, ",")
		if len(ips) > 0 {
			return strings.TrimSpace(ips[0])
		}
	}

	// Check X-Real-IP header
	if xri := r.Header.Get("X-Real-IP"); xri != "" {
		return xri
	}

	// Fall back to RemoteAddr
	ip, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		return r.RemoteAddr
	}
	return ip
}

// Server represents the main application server
type Server struct {
	supervisor          *actors.Supervisor
	wsManager           *comms.WebSocketManager
	datastore           *store.RedisDataStore
	postgresStore       *store.PostgresStore
	userHandlers        *handlers.UserHandlers
	friendsHandlers     *handlers.FriendsHandlers
	scheduler           *game.Scheduler
	lifecycleManager    *lifecycle.GameLifecycleManager
	eventBus            *events.EventBus
	mcpServer           *mcp.McpServer
	healthMonitor       *health.Monitor
	admissionController *admission.Controller
	adminHandlers       *admin.Handlers
	activeUserTracker   *admission.ActiveUserTracker
	authService         *auth.AuthService
	authHandlers        *auth.AuthHandlers
	rateLimiter         *rate.Limiter
	lobbyListRateLimiter *rate.Limiter
	joinLobbyRateLimiter *IPRateLimiter
}

// NewServer creates a new server instance
func NewServer() (*Server, error) {
	// Initialize structured logging
	logger.InitLogger()
	log := logger.GetLogger()
	log.Info("Initializing server")

	// Initialize Redis datastore
	redisAddr := os.Getenv("REDIS_ADDR")
	if redisAddr == "" {
		redisAddr = "localhost:6379"
	}

	redisPassword := os.Getenv("REDIS_PASSWORD")
	redisDB := 0

	datastore, err := store.NewRedisDataStore(redisAddr, redisPassword, redisDB)
	if err != nil {
		log.Error("Failed to create Redis datastore", "error", err, "addr", redisAddr)
		return nil, fmt.Errorf("failed to create datastore: %w", err)
	}
	log.Info("Connected to Redis", "addr", redisAddr)

	// Initialize PostgreSQL store
	postgresURL := os.Getenv("DATABASE_URL")
	if postgresURL == "" {
		postgresURL = "postgres://postgres:password@localhost:5432/alignment?sslmode=disable"
	}

	postgresStore, err := store.NewPostgresStore(postgresURL)
	if err != nil {
		log.Warn("Failed to connect to PostgreSQL, meta-game features will be disabled", "error", err, "url", postgresURL)
		postgresStore = nil
	} else {
		log.Info("Connected to PostgreSQL", "url", postgresURL)
	}

	// Create supervisor with application context
	ctx := context.Background()

	// Create event bus first
	eventBus := events.NewEventBus()

	// Create supervisor with event bus
	supervisor := actors.NewSupervisor(ctx, datastore, postgresStore, nil, eventBus) // Will set broadcaster later

	// Create active user tracker
	activeUserTracker := admission.NewActiveUserTracker()
	log.Info("Active user tracker created")

	// Create unified lifecycle manager
	lifecycleManager := lifecycle.NewGameLifecycleManager(ctx, datastore, nil, supervisor, eventBus, postgresStore, activeUserTracker)

	// Create scheduler (simplified - no longer needs session manager callback)
	scheduler := game.NewScheduler(func(timer game.Timer) {
		log.Info("Timer expired", "timer", timer)
		// Timer handling can be implemented later if needed
	})

	// Create WebSocket manager
	wsManager := comms.NewWebSocketManager(ctx, lifecycleManager)
	wsManager.SetDependencies(lifecycleManager, eventBus)
	wsManager.SetPostgresStore(postgresStore)
	wsManager.SetActionSemaphore(actionSemaphore)

	// Set the WebSocketManager as broadcaster for supervisor and lifecycle manager
	supervisor.SetBroadcaster(wsManager)
	// Note: lifecycleManager doesn't need a broadcaster - it uses the event bus

	// Create MCP server
	mcpServer := mcp.NewMcpServer(lifecycleManager)

	// Create health monitor
	healthMonitor := health.NewMonitor(health.DefaultConfig())
	log.Info("Health monitor created")

	// Create admission controller
	admissionController := admission.NewController(healthMonitor, datastore.Client())
	log.Info("Admission controller created")

	// Create auth service and handlers
	authService, err := auth.NewAuthService()
	if err != nil {
		log.Warn("Failed to create auth service, authentication will be disabled", "error", err)
		authService = nil
	} else {
		log.Info("Auth service created")
	}

	var authHandlers *auth.AuthHandlers
	if authService != nil {
		authHandlers = auth.NewAuthHandlers(authService)
		log.Info("Auth handlers created")
	}

	// Create admin handlers
	adminHandlers := admin.NewHandlers(supervisor, healthMonitor)
	log.Info("Admin handlers created")

	// Create user handlers if PostgreSQL is available
	var userHandlers *handlers.UserHandlers
	var friendsHandlers *handlers.FriendsHandlers
	if postgresStore != nil {
		userHandlers = handlers.NewUserHandlers(postgresStore)
		friendsHandlers = handlers.NewFriendsHandlers(postgresStore)
		// Set the WebSocket manager as the notification sender for friends handlers
		friendsHandlers.SetNotificationSender(wsManager)
	}

	server := &Server{
		supervisor:          supervisor,
		wsManager:           wsManager,
		datastore:           datastore,
		postgresStore:       postgresStore,
		userHandlers:        userHandlers,
		friendsHandlers:     friendsHandlers,
		scheduler:           scheduler,
		lifecycleManager:    lifecycleManager,
		eventBus:            eventBus,
		mcpServer:           mcpServer,
		healthMonitor:       healthMonitor,
		admissionController: admissionController,
		adminHandlers:       adminHandlers,
		activeUserTracker:   activeUserTracker,
		authService:         authService,
		authHandlers:        authHandlers,
		rateLimiter:         rate.NewLimiter(rate.Every(500*time.Millisecond), 20), // Allow 2 requests per second, burst of 20
		lobbyListRateLimiter: rate.NewLimiter(rate.Every(1*time.Second), 30), // More generous: 1 request per second, burst of 30
		joinLobbyRateLimiter: NewIPRateLimiter(rate.Every(1*time.Second), 10), // Per-IP: 1 join per second, burst of 10
	}

	return server, nil
}

// Start starts all server components
func (s *Server) Start() {
	log := logger.GetLogger()
	log.Info("Starting Alignment game server")

	// Start components in dependency order
	s.healthMonitor.Start()
	log.Info("Health monitor started")

	s.admissionController.Start()
	log.Info("Admission controller started")

	s.scheduler.Start()
	log.Info("Scheduler started")

	s.supervisor.Start()
	log.Info("Supervisor started")

	s.wsManager.Start()
	log.Info("WebSocket manager started")

	// Start cleanup routine for per-IP rate limiters
	go s.startRateLimiterCleanup()
	log.Info("Rate limiter cleanup started")

	log.Info("All components started successfully")
}

// startRateLimiterCleanup periodically cleans up stale rate limiters
func (s *Server) startRateLimiterCleanup() {
	ticker := time.NewTicker(10 * time.Minute) // Clean up every 10 minutes
	defer ticker.Stop()

	for range ticker.C {
		s.joinLobbyRateLimiter.CleanupStale()
	}
}

// Stop gracefully shuts down the server
func (s *Server) Stop() {
	log := logger.GetLogger()
	log.Info("Shutting down server")

	// Stop components in reverse dependency order
	s.supervisor.Stop()
	log.Info("Supervisor stopped")

	s.scheduler.Stop()
	log.Info("Scheduler stopped")

	s.admissionController.Stop()
	log.Info("Admission controller stopped")

	s.healthMonitor.Stop()
	log.Info("Health monitor stopped")

	s.datastore.Close()
	log.Info("Redis datastore closed")

	if s.postgresStore != nil {
		s.postgresStore.Close()
		log.Info("PostgreSQL store closed")
	}

	log.Info("Server stopped")
}

// HTTP handlers
func (s *Server) setupRoutes() {
	mux := http.NewServeMux()

	// Basic endpoints
	mux.HandleFunc("/health", s.healthHandler)
	mux.HandleFunc("/metrics", promhttp.Handler().ServeHTTP)
	mux.HandleFunc("/ws", s.wsManager.HandleWebSocket)
	mux.HandleFunc("/api/stats", s.statsHandler)
	mux.HandleFunc("/api/debug/event-types", s.debugEventTypesHandler)

	// Game endpoints with proper routing
	mux.HandleFunc("/api/games", s.gamesHandlerWithDifferentiatedRateLimit)
	mux.HandleFunc("POST /api/games/{gameId}/join", s.joinLobbyRateLimitMiddleware(s.joinLobbyHandler))

	// Admin endpoints
	s.adminHandlers.SetupRoutes()

	// Auth endpoints (only if auth service is available)
	if s.authHandlers != nil {
		mux.HandleFunc("/api/auth/login", s.authHandlers.LoginHandler)       // GET to start OAuth flow
		mux.HandleFunc("/api/auth/callback", s.authHandlers.CallbackHandler) // GET OAuth callback
		mux.HandleFunc("/api/auth/logout", s.authHandlers.LogoutHandler)     // POST to logout
		mux.HandleFunc("/api/me", s.authHandlers.MeHandler)                  // GET current user info
	} else {
		// Fallback /api/me endpoint when auth is disabled
		mux.HandleFunc("/api/me", s.unauthenticatedMeHandler)
	}

	// User profile endpoints (only if PostgreSQL is available)
	if s.userHandlers != nil {
		mux.HandleFunc("/api/users", s.userHandlers.CreateUser)             // POST to create user
		mux.HandleFunc("/api/users/me", s.userHandlers.GetUserProfile)      // GET user profile
		mux.HandleFunc("/api/users/me/equip", s.userHandlers.EquipItem)     // POST to equip items
		mux.HandleFunc("/api/users/me/kudos", s.userHandlers.GiveKudos)     // POST to give kudos
		mux.HandleFunc("/api/users/me/report", s.userHandlers.ReportPlayer) // POST to report player
		mux.HandleFunc("/api/users/me/block", s.userHandlers.BlockPlayer)   // POST to block player
	}

	// Friends system endpoints with proper routing (only if PostgreSQL is available)
	if s.friendsHandlers != nil {
		mux.HandleFunc("/api/friends", s.friendsHandlers.GetFriendsList)                       // GET friends list
		mux.HandleFunc("/api/friends/requests", s.friendsHandlers.SendFriendRequest)           // POST to send request
		mux.HandleFunc("POST /api/friends/requests/{requestId}/accept", s.friendsHandlers.AcceptFriendRequest) // Accept request
		mux.HandleFunc("DELETE /api/friends/requests/{requestId}", s.friendsHandlers.DeclineFriendRequest)     // Decline request
		mux.HandleFunc("/api/friends/remove", s.friendsHandlers.RemoveFriend)                  // DELETE to remove friend
		mux.HandleFunc("/api/friends/status", s.friendsHandlers.GetFriendsStatus)              // GET friends status
	}

	mux.HandleFunc("/test", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("Test endpoint works"))
	})
	// Swagger documentation endpoint
	mux.HandleFunc("/swagger/", httpSwagger.WrapHandler)

	// Set the mux as the default handler
	http.Handle("/", mux)
}

// rateLimitMiddleware applies rate limiting to HTTP endpoints
func (s *Server) rateLimitMiddleware(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !s.rateLimiter.Allow() {
			logger.GetLogger().Warn("Rate limit exceeded", "ip", r.RemoteAddr, "endpoint", r.URL.Path)
			http.Error(w, "Too many requests. Please try again later.", http.StatusTooManyRequests)
			return
		}
		next.ServeHTTP(w, r)
	}
}

// lobbyListRateLimitMiddleware applies more generous rate limiting for lobby listing
func (s *Server) lobbyListRateLimitMiddleware(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !s.lobbyListRateLimiter.Allow() {
			logger.GetLogger().Warn("Lobby list rate limit exceeded", "ip", r.RemoteAddr, "endpoint", r.URL.Path)
			http.Error(w, "Too many requests. Please try again later.", http.StatusTooManyRequests)
			return
		}
		next.ServeHTTP(w, r)
	}
}

// joinLobbyRateLimitMiddleware applies per-IP rate limiting for lobby joins
func (s *Server) joinLobbyRateLimitMiddleware(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		clientIP := getClientIP(r)
		limiter := s.joinLobbyRateLimiter.GetLimiter(clientIP)

		if !limiter.Allow() {
			logger.GetLogger().Warn("Join lobby rate limit exceeded", "ip", clientIP, "endpoint", r.URL.Path)
			http.Error(w, "Too many join requests. Please wait before trying again.", http.StatusTooManyRequests)
			return
		}
		next.ServeHTTP(w, r)
	}
}

// validateCreateLobbyRequest validates lobby creation parameters
func (s *Server) validateCreateLobbyRequest(req CreateLobbyRequest) error {
	// Validate UserID length and format
	if len(req.UserID) == 0 {
		return fmt.Errorf("user_id is required")
	}
	if len(req.UserID) > 100 {
		return fmt.Errorf("user_id too long (max 100 characters)")
	}

	// Validate PlayerName
	if len(req.PlayerName) == 0 {
		return fmt.Errorf("player_name is required")
	}
	if len(req.PlayerName) > 50 {
		return fmt.Errorf("player_name too long (max 50 characters)")
	}
	// Check for potentially malicious characters
	if containsSuspiciousChars(req.PlayerName) {
		return fmt.Errorf("player_name contains invalid characters")
	}

	// Validate LobbyName if provided
	if len(req.LobbyName) > 100 {
		return fmt.Errorf("lobby_name too long (max 100 characters)")
	}
	if req.LobbyName != "" && containsSuspiciousChars(req.LobbyName) {
		return fmt.Errorf("lobby_name contains invalid characters")
	}

	// Validate PlayerAvatar if provided
	if len(req.PlayerAvatar) > 50 {
		return fmt.Errorf("player_avatar too long (max 50 characters)")
	}

	return nil
}

// validateJoinLobbyRequest validates lobby join parameters
func (s *Server) validateJoinLobbyRequest(req JoinLobbyRequest) error {
	// Validate UserID
	if len(req.UserID) == 0 {
		return fmt.Errorf("user_id is required")
	}
	if len(req.UserID) > 100 {
		return fmt.Errorf("user_id too long (max 100 characters)")
	}

	// Validate PlayerName
	if len(req.PlayerName) == 0 {
		return fmt.Errorf("player_name is required")
	}
	if len(req.PlayerName) > 50 {
		return fmt.Errorf("player_name too long (max 50 characters)")
	}
	if containsSuspiciousChars(req.PlayerName) {
		return fmt.Errorf("player_name contains invalid characters")
	}

	// Validate PlayerAvatar if provided
	if len(req.PlayerAvatar) > 50 {
		return fmt.Errorf("player_avatar too long (max 50 characters)")
	}

	return nil
}

// containsSuspiciousChars checks for characters that might be used maliciously
func containsSuspiciousChars(s string) bool {
	// Check for control characters, excessive whitespace, or script-injection patterns
	for _, r := range s {
		if r < 32 && r != 9 && r != 10 && r != 13 { // Allow tab, newline, carriage return
			return true
		}
		// Check for common script injection patterns
		if r == '<' || r == '>' || r == '\'' || r == '"' || r == '&' {
			return true
		}
	}

	// Check for excessive whitespace
	if len(strings.TrimSpace(s)) == 0 {
		return true
	}

	return false
}

// HealthResponse represents the health check response
type HealthResponse struct {
	Status string      `json:"status" example:"healthy"`
	Stats  interface{} `json:"stats"`
}

// healthHandler handles health check requests
// @Summary Health check
// @Description Get server health status and supervisor statistics
// @Tags health
// @Produce json
// @Success 200 {object} HealthResponse
// @Router /health [get]
func (s *Server) healthHandler(w http.ResponseWriter, r *http.Request) {
	status := HealthResponse{
		Status: "healthy",
		Stats:  s.supervisor.GetStats(),
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(status)
}

// UnauthenticatedMeResponse represents the response for /api/me when auth is disabled
type UnauthenticatedMeResponse struct {
	IsAuthenticated bool `json:"is_authenticated"`
}

// unauthenticatedMeHandler handles /api/me requests when auth is disabled
func (s *Server) unauthenticatedMeHandler(w http.ResponseWriter, r *http.Request) {
	// Only allow GET requests
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	response := UnauthenticatedMeResponse{
		IsAuthenticated: false,
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(response)
}

func (s *Server) gamesHandler(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		s.listLobbies(w, r)
	case http.MethodPost:
		s.createLobby(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

// gamesHandlerWithDifferentiatedRateLimit applies different rate limits for GET vs POST on /api/games
func (s *Server) gamesHandlerWithDifferentiatedRateLimit(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		// Use more generous rate limiting for lobby listing
		s.lobbyListRateLimitMiddleware(s.listLobbies)(w, r)
	case http.MethodPost:
		// Use strict rate limiting for lobby creation
		s.rateLimitMiddleware(s.createLobby)(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

// LobbyListResponse represents the lobby list response
type LobbyListResponse struct {
	Lobbies []interface{} `json:"lobbies"`
}

// listLobbies handles lobby listing requests
// @Summary List available lobbies
// @Description Get a list of all available game lobbies
// @Tags lobbies
// @Produce json
// @Success 200 {object} LobbyListResponse
// @Router /api/games [get]
func (s *Server) listLobbies(w http.ResponseWriter, r *http.Request) {
	lobbies := s.lifecycleManager.GetLobbyList()

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(LobbyListResponse{
		Lobbies: lobbies,
	})
}

// CreateLobbyRequest represents the request to create a new lobby
type CreateLobbyRequest struct {
	UserID                   string `json:"user_id" example:"guest:abc123" binding:"required"`
	LobbyName                string `json:"lobby_name" example:"My Game Lobby"`
	PlayerName               string `json:"player_name" example:"John Doe" binding:"required"`
	PlayerAvatar             string `json:"player_avatar" example:"avatar1"`
	IsPrivate                bool   `json:"is_private" example:"false"`
	PlayAsAI                 bool   `json:"play_as_ai,omitempty"`
	InitialAlignedHumanCount int    `json:"initial_aligned_human_count,omitempty"`
}

// CreateLobbyResponse represents the response after creating a lobby
type CreateLobbyResponse struct {
	GameID       string `json:"game_id" example:"abc123"`
	PlayerID     string `json:"player_id" example:"player456"`
	SessionToken string `json:"session_token" example:"token789"`
}

// ErrorResponse represents an error response
type ErrorResponse struct {
	Error string `json:"error" example:"Player name is required"`
}

// createLobby handles lobby creation requests
// @Summary Create a new lobby
// @Description Create a new game lobby with the requesting player as host
// @Tags lobbies
// @Accept json
// @Produce json
// @Param request body CreateLobbyRequest true "Lobby creation request"
// @Success 201 {object} CreateLobbyResponse
// @Failure 400 {object} ErrorResponse
// @Failure 500 {object} ErrorResponse
// @Router /api/games [post]
func (s *Server) createLobby(w http.ResponseWriter, r *http.Request) {
	log := logger.WithField("endpoint", "createLobby")
	var req CreateLobbyRequest

	// Read and decode the request body
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		log.Warn("Invalid request body", "error", err)
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	// Validate request parameters to prevent abuse
	if err := s.validateCreateLobbyRequest(req); err != nil {
		log.Warn("Invalid create lobby request", "error", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Check admission control (using player name as user ID for simplicity)
	requestBody, _ := json.Marshal(req)
	if err := s.admissionController.CheckAdmission(req.PlayerName, requestBody); err != nil {
		if waitlistErr, ok := err.(*admission.WaitlistError); ok {
			admission.WriteWaitlistResponse(w, waitlistErr)
			return
		}
		log.Error("Admission control error", "error", err)
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}

	if req.LobbyName == "" {
		req.LobbyName = fmt.Sprintf("%s's Game", req.PlayerName)
	}

	if req.UserID == "" {
		log.Warn("User ID is required")
		http.Error(w, "User ID is required", http.StatusBadRequest)
		return
	}

	if req.PlayerName == "" {
		log.Warn("Player name is required")
		http.Error(w, "Player name is required", http.StatusBadRequest)
		return
	}

	// Determine the actual user ID (prefer authenticated user over guest)
	actualUserID := req.UserID
	if s.authHandlers != nil {
		if authUserID, err := s.authHandlers.GetAuthenticatedUserID(r); err == nil {
			actualUserID = authUserID
			log.Info("Using authenticated user ID instead of guest ID", "auth_user_id", authUserID, "guest_id", req.UserID)
		}
	}

	log.Info("Creating lobby", "user_id", actualUserID, "player_name", req.PlayerName, "lobby_name", req.LobbyName, "is_private", req.IsPrivate)

	// Check single-session rule - generate a temporary lobby ID for the check
	tempLobbyID := "CREATING"
	if err := s.activeUserTracker.CheckSingleSession(actualUserID, tempLobbyID); err != nil {
		log.Warn("Single-session rule violation", "user_id", actualUserID, "error", err)
		http.Error(w, "You are already in an active game session", http.StatusConflict)
		return
	}

	// Call the new, centralized method in the GameLifecycleManager
	// This ensures only one hostPlayerID is generated and used consistently
	lobbyID, hostPlayerID, sessionToken, err := s.lifecycleManager.CreateLobbyViaHTTP(actualUserID, req.PlayerName, req.LobbyName, req.PlayerAvatar, req.IsPrivate)
	if err != nil {
		log.Error("Failed to create lobby", "error", err, "player_name", req.PlayerName)
		http.Error(w, fmt.Sprintf("Failed to create lobby: %v", err), http.StatusInternalServerError)
		return
	}

	// Record metrics
	metrics.RecordLobbyCreated()

	// Add user to active session tracker
	if err := s.activeUserTracker.AddUserSession(actualUserID, lobbyID, hostPlayerID); err != nil {
		log.Error("Failed to add user to active session tracker", "error", err, "user_id", actualUserID)
		// Don't fail the request, just log the error
	}

	response := CreateLobbyResponse{
		GameID:       lobbyID,
		PlayerID:     hostPlayerID,
		SessionToken: sessionToken,
	}

	log.Info("Lobby created successfully", "lobby_id", lobbyID, "host_player_id", hostPlayerID, "user_id", actualUserID)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(response)
}

// joinLobbyHandler handles lobby join requests using path parameters
func (s *Server) joinLobbyHandler(w http.ResponseWriter, r *http.Request) {
	gameID := r.PathValue("gameId")
	if gameID == "" {
		http.Error(w, "Invalid game ID", http.StatusBadRequest)
		return
	}
	s.joinLobby(w, r, gameID)
}

// JoinLobbyRequest represents the request to join an existing lobby
type JoinLobbyRequest struct {
	UserID       string `json:"user_id" example:"guest:def456" binding:"required"`
	PlayerName   string `json:"player_name" example:"Jane Doe" binding:"required"`
	PlayerAvatar string `json:"player_avatar" example:"avatar2"`
}

// JoinLobbyResponse represents the response after joining a lobby
type JoinLobbyResponse struct {
	GameID       string `json:"game_id" example:"abc123"`
	PlayerID     string `json:"player_id" example:"player789"`
	SessionToken string `json:"session_token" example:"token456"`
}

// joinLobby handles lobby join requests
// @Summary Join an existing lobby
// @Description Join an existing game lobby as a player
// @Tags lobbies
// @Accept json
// @Produce json
// @Param gameId path string true "Game ID"
// @Param request body JoinLobbyRequest true "Join lobby request"
// @Success 200 {object} JoinLobbyResponse
// @Failure 400 {object} ErrorResponse
// @Failure 404 {object} ErrorResponse "Lobby not found"
// @Failure 409 {object} ErrorResponse "Lobby is full or not accepting players"
// @Failure 500 {object} ErrorResponse
// @Router /api/games/{gameId}/join [post]
func (s *Server) joinLobby(w http.ResponseWriter, r *http.Request, gameID string) {
	log := logger.WithFields(map[string]interface{}{
		"endpoint": "joinLobby",
		"game_id":  gameID,
	})
	var req JoinLobbyRequest

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		log.Warn("Invalid request body", "error", err)
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	// Validate request parameters to prevent abuse
	if err := s.validateJoinLobbyRequest(req); err != nil {
		log.Warn("Invalid join lobby request", "error", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Determine the actual user ID (prefer authenticated user over guest)
	actualUserID := req.UserID
	if s.authHandlers != nil {
		if authUserID, err := s.authHandlers.GetAuthenticatedUserID(r); err == nil {
			actualUserID = authUserID
			log.Info("Using authenticated user ID instead of guest ID", "auth_user_id", authUserID, "guest_id", req.UserID)
		}
	}

	log.Info("Player joining lobby", "user_id", actualUserID, "player_name", req.PlayerName, "game_id", gameID)

	// Check single-session rule
	if err := s.activeUserTracker.CheckSingleSession(actualUserID, gameID); err != nil {
		log.Warn("Single-session rule violation", "user_id", actualUserID, "error", err)
		http.Error(w, "You are already in an active game session", http.StatusConflict)
		return
	}

	playerID, sessionToken, err := s.lifecycleManager.JoinLobby(gameID, actualUserID, req.PlayerName, req.PlayerAvatar)
	if err != nil {
		log.Warn("Failed to join lobby", "error", err, "player_name", req.PlayerName)
		switch err.Error() {
		case "lobby not found":
			http.Error(w, "Lobby not found", http.StatusNotFound)
		case "lobby is not accepting new players":
			http.Error(w, "Lobby is not accepting new players", http.StatusConflict)
		case "lobby is full":
			http.Error(w, "Lobby is full", http.StatusConflict)
		default:
			http.Error(w, "Failed to join lobby", http.StatusInternalServerError)
		}
		return
	}

	// Record metrics
	metrics.RecordPlayerJoined()

	// Add user to active session tracker
	if err := s.activeUserTracker.AddUserSession(actualUserID, gameID, playerID); err != nil {
		log.Error("Failed to add user to active session tracker", "error", err, "user_id", actualUserID)
		// Don't fail the request, just log the error
	}

	response := JoinLobbyResponse{
		GameID:       gameID,
		PlayerID:     playerID,
		SessionToken: sessionToken,
	}

	log.Info("Player joined lobby successfully", "player_id", playerID, "player_name", req.PlayerName, "user_id", actualUserID)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(response)
}

// StatsResponse represents the server statistics response
type StatsResponse struct {
	Supervisor interface{} `json:"supervisor"`
	Scheduler  int         `json:"scheduler"`
}

// statsHandler handles server statistics requests
// @Summary Get server statistics
// @Description Get detailed server statistics including supervisor and scheduler information
// @Tags health
// @Produce json
// @Success 200 {object} StatsResponse
// @Router /api/stats [get]
func (s *Server) statsHandler(w http.ResponseWriter, r *http.Request) {
	stats := StatsResponse{
		Supervisor: s.supervisor.GetStats(),
		Scheduler:  len(s.scheduler.GetActiveTimers()),
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(stats)
}

// EventTypesResponse represents the debug event types response
type EventTypesResponse struct {
	EventTypes   []string `json:"event_types" example:"GAME_CREATED,PLAYER_JOINED,VOTE_CAST"`
	ActionTypes  []string `json:"action_types" example:"CREATE_GAME,JOIN_GAME,SUBMIT_VOTE"`
	TotalEvents  int      `json:"total_events" example:"94"`
	TotalActions int      `json:"total_actions" example:"22"`
}

// debugEventTypesHandler handles debug event types requests
// @Summary Get all event and action types
// @Description Get a comprehensive list of all available event and action types in the system for debugging and contract verification
// @Tags debug
// @Produce json
// @Success 200 {object} EventTypesResponse
// @Failure 405 {object} ErrorResponse "Method not allowed"
// @Router /api/debug/event-types [get]
func (s *Server) debugEventTypesHandler(w http.ResponseWriter, r *http.Request) {
	// Only allow GET requests
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Convert the core.EventTypeValues to string slice
	eventTypes := make([]string, len(core.EventTypeValues))
	for i, eventType := range core.EventTypeValues {
		eventTypes[i] = string(eventType)
	}

	// Convert the core.ActionTypeValues to string slice
	actionTypes := make([]string, len(core.ActionTypeValues))
	for i, actionType := range core.ActionTypeValues {
		actionTypes[i] = string(actionType)
	}

	response := EventTypesResponse{
		EventTypes:   eventTypes,
		ActionTypes:  actionTypes,
		TotalEvents:  len(eventTypes),
		TotalActions: len(actionTypes),
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(response)
}


func main() {
	// Parse command-line flags
	mcpMode := flag.Bool("mcp", false, "Run in MCP mode (Model Context Protocol)")
	flag.Parse()

	// Create server
	server, err := NewServer()
	if err != nil {
		log.Fatalf("Failed to create server: %v", err)
	}

	if *mcpMode {
		// Run MCP server on stdio
		logger.GetLogger().Info("Starting server in MCP mode")
		server.mcpServer.Run()
		return
	}

	// Standard HTTP/WebSocket server mode
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	// Setup routes
	server.setupRoutes()

	// Start server components
	server.Start()

	// Setup graceful shutdown
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)

	go func() {
		<-c
		logger.GetLogger().Info("Received shutdown signal")
		server.Stop()
		os.Exit(0)
	}()

	fmt.Printf("Alignment server starting on port %s\n", port)
	fmt.Println("WebSocket endpoint: /ws")
	fmt.Println("API endpoints:")
	fmt.Println("  GET  /health")
	fmt.Println("  GET  /metrics               - Prometheus metrics")
	fmt.Println("  GET  /api/games               - List lobbies")
	fmt.Println("  POST /api/games              - Create lobby")
	fmt.Println("  POST /api/games/{gameId}/join - Join lobby")
	fmt.Println("  GET  /api/stats")
	fmt.Println("  GET  /api/debug/event-types   - List event and action types")
	fmt.Println("Admin endpoints (requires authentication):")
	fmt.Println("  GET  /admin                  - Admin dashboard UI")
	fmt.Println("  GET  /admin/status           - Server status")
	fmt.Println("  GET  /admin/games            - List active games")
	fmt.Println("  GET  /admin/games/{id}/state - Get game state")
	fmt.Println("  DELETE /admin/games/{id}     - Terminate game")

	logger.GetLogger().Info("Server listening", "port", port)
	if err := http.ListenAndServe(":"+port, nil); err != nil {
		log.Fatal("Server failed to start:", err)
	}
}