name: End-to-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        # FIX: Standardize on the same Redis version used in the main CI workflow.
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/e2e/requirements.txt

      - name: Build and run services
        run: docker-compose -f docker-compose.dev.yml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for backend..."
          while ! nc -z localhost 8080; do
            sleep 1
          done
          echo "Backend is up!"
          echo "Waiting for frontend..."
          while ! nc -z localhost 5173; do
            sleep 1
          done
          echo "Frontend is up!"

      - name: Run E2E tests
        run: pytest tests/e2e/test_full_game.py

      - name: Stop services
        if: always()
        run: docker-compose -f docker-compose.dev.yml down